### ISSUE TITLE
What if user send chitchat data that doesn't need a tool

### ISSUE THREAD

**Issue by AtmehEsraa** [gravitymonkey/give_up_the_func#1]
What if user send chitchat data that doesn't need a tool

**Comment by gravitymonkey** [comment]
Just did an update which returns `response` (which is an OpenAI compatible `openai.types.chat.chat_completion.ChatCompletion`), and, just like an OpenAI response, the value for `function_call` as `null` if there is no tool usage detected. @AtmehEsraa 

<img width="453" alt="Screenshot 2024-06-07 at 8 56 40 AM" src="https://github.com/gravitymonkey/give_up_the_func/assets/342827/5b0d803c-a4ae-4ff7-a445-bacd8607a608">
